name: Build Hadoop

on:
  workflow_dispatch: # add manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Build Hadoop
        run: |
          git clone https://github.com/apache/hadoop
          cd hadoop
          git checkout a3b9c37
          sed -i 's/docker run -i -t/docker run -i/g' ./dev-support/bin/create-release
          ./dev-support/bin/create-release --docker --mvncache --artifactsdir || { echo "Failed to checkout commit"; }
          gh release create "temp" \
            --title "temp" \
            --prerelease \
            --notes "temp"
          gh release upload "temp" ./patchprocess/mvn_install.log
          gh release upload "temp" ./target/artifacts/*.tar.gz
